### ISSUE TITLE
Boot errors with enable_crash_reports

### ISSUE THREAD

**Issue by polmiro** [ForzaElixir/rollbax#100]
How would you suggest handling boot errors when `enable_crash_reports` is activated? My team has run into this situation a few times, which in matter of seconds or minutes tens of thousands of errors have been reported to Rollbar because of a core process not being able to start (usually a configuration issue, for example: new database was not yet provisioned so the corresponding Ecto.Repo crashes).

I would like to implement some kind of control / back off to avoid generating so many error reports at once in these circumstances. I wonder if anyone has run into this problem before and already found a good solution for it. I suspect `Rollbax.Reporter` would be the right place to resolve this but any guidance would be appreciated too.

Thank you!

**Comment by thbar** [comment]
@polmiro currently I'm "just" setting an appropriate quota on the Rollbar token. But I'd be curious to hear about what you may have implemented to mitigate this otherwise? Thanks!

**Comment by polmiro** [comment]
@thbar I have not found any way to mitigate this. Implementing something for it fell down our priority list. Thanks for your suggestion of using Rollbar token quotas. For some reason, I never head about it 🙇 😄. This is probably something not worth adding to the library itself so I will close this issue.

**Comment by thbar** [comment]
@polmiro that you didn't have to implement anything is a useful feedback, thank you!

I'll just use quotas then. Many thanks!
