### ISSUE TITLE
Enabled must be {true, false, :log}

### ISSUE THREAD

**Issue by maxbeizer** [ForzaElixir/rollbax#106]
Rollbax Version: 0.9.2
Elixir version: 1.6.0

Just got bit by a subtle issue. My config looks like this

```elixir
config :rollbax,
  enabled: System.get_env("ROLLBAR_ACCESS_TOKEN"),
  access_token: System.get_env("ROLLBAR_ACCESS_TOKEN"),
  environment: System.get_env("MIX_ENV")
```

That leads to 

```
 GenServer Rollbax.Client terminating
** (FunctionClauseError) no function clause matching in Rollbax.Client.handle_cast/2
    (rollbax) lib/rollbax/client.ex:62: Rollbax.Client.handle_cast({:emit, {"info", 1547222886, %{<redacted>}, enabled: <redact_access_token>, hackney_responses: %{}, url: "https://api.rollbar.com/api/1/item
/"})
```

Importantly: 
```
enabled: <redact_access_token> 
```

So the Client takes the config values literally. I was expecting a truthy value to work here.

Could I send a PR that either
1. allows the enabled value to `{true, false, :log, truthy}` OR
2. logs an error from the Client that the enabled config is invalid OR
3. at least updates the README with the allowed values

I vote for allowing the value to be truthy since, I'd generally only want rollbax to be enabled if the access token is present

**Comment by whatyouhide** [comment]
I am against allowing `:enabled` to be anything. I would prefer 3 or maybe a runtime error at application start, where we could validate the configuration. Thoughts?

**Comment by maxbeizer** [comment]
> runtime error at application start

I'm all for failing early. I can do that and update the README/docs if you'd like
