### ISSUE TITLE
Support "people tracking" / "person tracking" for non-custom exceptions

### ISSUE THREAD

**Issue by tensiondriven** [ForzaElixir/rollbax#113]
I see in the source code that a `person` value can be passed for custom exceptions:

https://github.com/ForzaElixir/rollbax/blob/master/lib/rollbax.ex#L146

I'm wondering if its possible to configure Rollbax to populate Person/People information for exceptions which are not custom, as described here:

https://docs.rollbar.com/docs/person-tracking

i.e. something similar to the Ruby gem's notion of a `person_method`:

https://rollbar.com/docs/notifier/rollbar-gem/#person-tracking

Is it possible?

**Comment by whatyouhide** [comment]
It's possible yes, but I have no ideas on the API and I don't have bandwidth to implement this right now. If you want to contribute this, I would suggest that you come up with a detailed proposal of how the API would look like and then if we want to move forward with that we'll go with the implementation. Wdyt?

**Comment by tensiondriven** [comment]
I love the idea; I've added it to my backlog, but can't give a projection on when I might have something.  I think we can close this for now.
