### ISSUE TITLE
Add support for Person Tracking

### ISSUE THREAD

**Issue by shankardevy** [ForzaElixir/rollbax#119]
Rollbar gem for RoR or Django has support for tracking people affected by a bug. I think it's a cool feature to have it in Rollbax as well.

Details here: https://docs.rollbar.com/docs/person-tracking

Would a PR be accepted for this?

**Comment by qcam** [comment]
@shankardevy `person` can be added in the occurrence data in your Plug error handler. Example can be found at https://hexdocs.pm/rollbax/using-rollbax-in-plug-based-applications.html.

**Comment by shankardevy** [comment]
Thanks!
