### ISSUE TITLE
Feature request on patching functions

### ISSUE THREAD

**Issue by asiniy** [ForzaElixir/rollbax#65]
@whatyouhide wdyt about stuff like that:

``` elixir
defmodule MyApp do
  use Rollbax, track_functions: [do_something: 1]

  def do_something(param) do
    #
  end
end
```

This `tracking` allow us to write better code.

**Comment by whatyouhide** [comment]
@asiniy what would `:track_functions` do? What would happen when a function is "tracked"?

**Comment by asiniy** [comment]
@whatyouhide it will track the function by wrapping it by

``` elixir
try
  # original do_something function
rescue
  exception ->
        Rollbax.report(:error, exception, System.stacktrace())
end
```

Rollbax boilerplate code spoils the implementation of the function.

**Comment by whatyouhide** [comment]
While I'm not keen on the API, it's something we can investigate. Thanks for the proposal 👍

**Comment by asiniy** [comment]
Another interesting point here is specializing `env` here

**Comment by whatyouhide** [comment]
Thanks for the proposal @asiniy. Three years have passed and we haven't received more feedback or requests on this feature. You're welcome to send a PR with a prototype implementation, but for now I'll close this issue. Feel free to reopen if you want to continue this discussion!
